# Generated by Django 3.2 on 2021-04-17 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=255)),
                ('duration_minutes', models.IntegerField()),
                ('url', models.CharField(default='', max_length=2038)),
            ],
        ),
        migrations.CreateModel(
            name='theater',
            fields=[
                ('theater_id', models.AutoField(primary_key=True, serialize=False)),
                ('theater_name', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=2000)),
                ('pin_code', models.CharField(max_length=10)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviebooking.city')),
            ],
        ),
        migrations.CreateModel(
            name='theater_movies_rel',
            fields=[
                ('theater_movies_id', models.AutoField(primary_key=True, serialize=False)),
                ('show_start', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviebooking.movie')),
                ('theater_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviebooking.theater')),
            ],
        ),
        migrations.CreateModel(
            name='theater_seats',
            fields=[
                ('theater_seats_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_no', models.CharField(default='NA', max_length=10)),
                ('theater_movies_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviebooking.theater_movies_rel')),
            ],
        ),
        migrations.CreateModel(
            name='user_bookings',
            fields=[
                ('user_bookings_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_number', models.IntegerField()),
                ('transaction_mode', models.CharField(max_length=100)),
                ('amount_paid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('full_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='user_seats',
            fields=[
                ('user_seats_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='NA', max_length=100)),
                ('theater_seats_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviebooking.theater_seats')),
                ('user_bookings_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviebooking.user_bookings')),
            ],
        ),
    ]
